# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Set library preference based on BUILD_SHARED_LIBS
#
if( BUILD_SHARED_LIBS)
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()

#
# Generated from sourcetree: 9B1EEDAF-5103-4E5C-B280-25EB86FCA40E;mulle-sprintf;no-cmake-loader,no-cmake-searchpath,no-import,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-sprintf no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-sprintf no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-sprintf no-cmake-sdk-<name>`
#
if( COLLECT_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES "mulle-sprintf")
else()
   if( NOT MULLE__SPRINTF_LIBRARY)
      foreach( _TMP_MULLE__SPRINTF_LIBRARY_TARGET mulle-sprintf)
         if( TARGET ${_TMP_MULLE__SPRINTF_LIBRARY_TARGET})
            set( MULLE__SPRINTF_LIBRARY ${_TMP_MULLE__SPRINTF_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__SPRINTF_LIBRARY)
         find_library( MULLE__SPRINTF_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-sprintf${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-sprintf${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-sprintf${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-sprintf${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-sprintf
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__SPRINTF_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__SPRINTF_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-sprintf${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-sprintf${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-sprintf${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-sprintf${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-sprintf
            )
         endif()
      endif()
      message( STATUS "MULLE__SPRINTF_LIBRARY is ${MULLE__SPRINTF_LIBRARY}")
   endif()
   if( MULLE__SPRINTF_LIBRARY)
         #
         # Add MULLE__SPRINTF_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-sprintf no-cmake-add`
         #
         if( NOT ${MULLE__SPRINTF_LIBRARY} IN_LIST ALL_LOAD_DEPENDENCY_LIBRARIES)
            list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE__SPRINTF_LIBRARY})
         endif()
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-sprintf no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__SPRINTF_ROOT "${MULLE__SPRINTF_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__SPRINTF_ROOT "${_TMP_MULLE__SPRINTF_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-sprintf no-cmake-dependency`
         #
         foreach( _TMP_MULLE__SPRINTF_NAME "mulle-sprintf")
            set( _TMP_MULLE__SPRINTF_DIR "${_TMP_MULLE__SPRINTF_ROOT}/include/${_TMP_MULLE__SPRINTF_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__SPRINTF_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__SPRINTF_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__SPRINTF_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__SPRINTF_DIR}")
               #
               unset( MULLE__SPRINTF_DEFINITIONS)
               unset( MULLE__SPRINTF_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__SPRINTF_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__SPRINTF_DEFINITIONS})
               include( "${_TMP_MULLE__SPRINTF_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__SPRINTF_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__SPRINTF_DIR} not found")
            endif()
         endforeach()
   else()
      # Disable with: `mulle-sourcetree mark mulle-sprintf no-require-link`
      message( SEND_ERROR "MULLE__SPRINTF_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-sprintf${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-sprintf${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-sprintf${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-sprintf${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-sprintf")
   endif()
endif()
